language: clojure
lein: lein2
script:
  - lein2 install
  - lein2 new mr-clojure test-api --to-dir target/test-api
  - lein2 new mr-clojure test-webapp --to-dir target/test-webapp -- --reagent-webapp
